# Project

### Initialization

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from tqdm import tqdm
import time

## 1. Classification, weight sharing, auxiliary losses

In [6]:
from dlc_practical_prologue import generate_pair_sets
N = 1000
epochs = 25

In [9]:
a = generate_pair_sets(N)

In [28]:
a[2]

tensor([[7, 9],
        [1, 8],
        [5, 3],
        ...,
        [2, 7],
        [2, 0],
        [8, 1]])

## 2. Mini deep-learning framework

In [29]:
import math
from torch import empty
torch.set_grad_enabled(False)

You should implement at least the modules Linear (fully connected layer), ReLU, Tanh, Sequential
to combine several modules in basic sequential structure, and LossMSE to compute the MSE loss

In [ ]:
def generate_set(N):
    train_input = torch.empty
    train_target =
    test_input =
    test_target =    

In [206]:
def generate_disk_set(N):
    
    # Generate train sets of 2 uniform distributions on [0,1]x[0,1]
    train_input = torch.empty(N, 2).uniform_(0, 1)
    test_input = torch.empty(N, 2).uniform_(0, 1)
    
    recenter = torch.tensor([0.5, 0.5]) # to act as if the train data was centered around 0, to ease the following computation
    
    # Generate the target tensors filled with 1 if datapoint is inside of specific circle
    train_target = (-(train_input - recenter).pow(2).sum(1).sqrt().sub(1 / math.sqrt(2 * math.pi))).sign().add(1).div(2).int()
    test_target = (-(train_input - recenter).pow(2).sum(1).sqrt().sub(1 / math.sqrt(2 * math.pi))).sign().add(1).div(2).int()
    
    return train_input, test_input, train_target,test_target

In [168]:
input = torch.empty(N, 2).uniform_(0, 1)

In [210]:
a = generate_disc_set(N)
a

(tensor([[0.6239, 0.4620],
         [0.4435, 0.2048],
         [0.6534, 0.1526],
         ...,
         [0.9025, 0.1418],
         [0.7172, 0.2822],
         [0.8464, 0.6788]]),
 tensor([[0.9338, 0.6325],
         [0.0889, 0.7811],
         [0.3600, 0.9220],
         ...,
         [0.0147, 0.8352],
         [0.4646, 0.7292],
         [0.6887, 0.7567]]),
 tensor([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
         1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
         1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
         1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
         0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
         0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
         0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
         1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,

In [46]:
a = torch.empty(N, 2).uniform_(0, 1).pow(2).sum(1)
a

tensor([[0.1185, 0.8120],
        [0.1680, 0.3330],
        [0.6334, 0.8082],
        ...,
        [0.0145, 0.3900],
        [0.5582, 0.4001],
        [0.7525, 0.8462]])

In [ ]:
class Module (object):
    
    def forward (self, *input):
        raise NotImplementedError
        
    def backward (self, *gradwrtoutput):
        raise NotImplementedError
        
    def param (self):
        return []

In [ ]:
class Linear(Module):
    """
    Linear layer
    """

    def __init__(self, in_feats, out_feats):
        self.weights = torch.empty((in_feats, out_feats))
        self.bias = torch.empty((1, out_feats))

    def forward(self, x):
        self.input = x
        output = x @ self.weights + self.bias
        return output

    def backward(self, dy):
        pass

    def params(self):
        return [self.weights, self.bias]

In [ ]:
# https://www.kdnuggets.com/2020/09/implementing-deep-learning-library-scratch-python.html








class Linear(Function):
    def __init__(self, in_dim, out_dim):
        self.weights = Tensor((in_dim,out_dim))
        self.bias    = Tensor((1, out_dim))
        self.type = 'linear'

    def forward(self,x):
        output = np.dot(x,self.weights.data)+self.bias.data
        self.input = x 
        return output

    def backward(self,d_y):
        self.weights.grad += np.dot(self.input.T,d_y)
        self.bias.grad    += np.sum(d_y,axis=0,keepdims=True)
        grad_input         = np.dot(d_y,self.weights.data.T)
        return grad_input

    def getParams(self):
        return [self.weights,self.bias]

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
class SGD(Optimizer):
    def __init__(self,parameters,lr=.001,weight_decay=0.0,momentum = .9):
        super().__init__(parameters)
        self.lr           = lr
        self.weight_decay = weight_decay
        self.momentum     = momentum
        self.velocity     = []
        for p in parameters:
            self.velocity.append(np.zeros_like(p.grad))

    def step(self):
        for p,v in zip(self.parameters,self.velocity):
            v = self.momentum*v+p.grad+self.weight_decay*p.data
            p.data=p.data-self.lr*v
            
class Model():
    def __init__(self):
        self.computation_graph = []
        self.parameters        = []

    def add(self,layer):
        self.computation_graph.append(layer)
        self.parameters+=layer.getParams()

    def __innitializeNetwork(self):
        for f in self.computation_graph:
            if f.type=='linear':
                weights,bias = f.getParams()
                weights.data = .01*np.random.randn(weights.data.shape[0],weights.data.shape[1])
                bias.data    = 0.

    def fit(self,data,target,batch_size,num_epochs,optimizer,loss_fn):
        loss_history = []
        self.__innitializeNetwork()
        data_gen = DataGenerator(data,target,batch_size)
        itr = 0
        for epoch in range(num_epochs):
            for X,Y in data_gen:
                optimizer.zeroGrad()
                for f in self.computation_graph: X=f.forward(X)
                loss = loss_fn.forward(X,Y)
                grad = loss_fn.backward()
                for f in self.computation_graph[::-1]: grad = f.backward(grad) 
                loss_history+=[loss]
                print("Loss at epoch = {} and iteration = {}: {}".format(epoch,itr,loss_history[-1]))
                itr+=1
                optimizer.step()
        
        return loss_history
    
    def predict(self,data):
        X = data
        for f in self.computation_graph: X = f.forward(X)
        return X

import dl_numpy as DL
import utilities

batch_size        = 20
num_epochs        = 200
samples_per_class = 100
num_classes       = 3
hidden_units      = 100
data,target       = utilities.genSpiralData(samples_per_class,num_classes)
model             = utilities.Model()
model.add(DL.Linear(2,hidden_units))
model.add(DL.ReLU())
model.add(DL.Linear(hidden_units,num_classes))
optim   = DL.SGD(model.parameters,lr=1.0,weight_decay=0.001,momentum=.9)
loss_fn = DL.SoftmaxWithLoss()
model.fit(data,target,batch_size,num_epochs,optim,loss_fn)
predicted_labels = np.argmax(model.predict(data),axis=1)
accuracy         = np.sum(predicted_labels==target)/len(target)
print("Model Accuracy = {}".format(accuracy))
utilities.plot2DDataWithDecisionBoundary(data,target,model)